const banks = {
  kha:{name:'Kha',caption:'12 câu thực hành sơ cấp cứu',topics:{'Thực hành':['Thực hành phương pháp băng vết thương ở đỉnh đầu (băng bằng băng cuộn).','Thực hành băng sơ cứu thương ở một mắt (băng bằng băng cuộn).','Thực hành băng vết thương ở trên mu bàn tay (băng bằng băng cuộn).','Thực hành băng vết thương ở giữa gan bàn chân (băng bằng băng cuộn).','Thực hành phương pháp cấp cứu nạn nhân bị điện giật và ngất.','Thực hành phương pháp cố định gãy xương đùi kín.','Thực hành phương pháp cố định gãy xương cẳng chân hở.','Thực hành phương pháp cố định gãy xương cẳng tay hở.','Thực hành phương pháp cấp cứu nạn nhân bị lòi ruột ở bụng.','Thực hành phương pháp cấp cứu nạn nhân bị thủng lồng ngực bằng băng cuộn.','Thực hành phương pháp cấp cứu nạn nhân bị say nóng hoặc say nắng.','Thực hành phương pháp cố định gãy xương hàm.']}},
  tu:{name:'Tú',caption:'12 câu điện · 8 câu nước',topics:{'Điện':['Nêu định nghĩa “Mối nguy”, “Nhận diện mối nguy” và “Đánh giá rủi ro”; nêu nguyên tắc chung đánh giá rủi ro trước khi làm việc.','Nêu trình tự bắt buộc khi thực hiện biện pháp kỹ thuật chuẩn bị nơi làm việc phải cắt điện.','Theo Nghị định 62/2025/NĐ-CP, trình bày những việc được làm theo bậc an toàn.','Trình bày trách nhiệm của Người giám sát an toàn điện tại hiện trường theo Quy trình An toàn 278/QĐ-EVN năm 2026.','Nêu khoảng cách an toàn về điện tối thiểu tương ứng các cấp điện áp từ hạ áp đến 500 kV.','Khi chặt cây, tỉa cành để giải phóng hành lang đường dây đang có điện, cần thực hiện các biện pháp kỹ thuật nào?','Nêu các bước lắp đặt công tơ điện tại hiện trường và thời hạn nghiệm thu sau thi công.','Nêu 4 nguyên tắc an toàn cơ bản khi làm việc trên lưới điện.','Nêu trách nhiệm phối hợp an toàn giữa đơn vị điện lực và đơn vị viễn thông/truyền hình cáp khi làm việc trên hàng cột điện lực.','Khi sửa chữa thiết bị trên cột điện có đèn đường đi chung, đơn vị công tác cần lưu ý gì về an toàn điện?','Quy định về thời hạn lưu trữ, quản lý Phiếu công tác và Lệnh công tác sau khi hoàn thành như thế nào?','Nêu biện pháp chống dòng điện phản hồi nguy hiểm từ phía khách hàng khi làm việc trên đường dây hạ thế đã cắt điện.'],'Nước':['Motor bơm 3 pha có dòng điện không cân bằng: nêu nguyên nhân, cách kiểm tra và hướng xử lý.','Nêu các trường hợp phải dừng ngay máy bơm khi đang vận hành.','Trình bày quy trình tháo máy bơm ly tâm trục ngang để bảo trì.','Trình bày quy trình lắp máy bơm ly tâm trục ngang.','Trình bày lưu ý trong quá trình tháo, lắp các loại máy bơm.','Kiểm tra motor trước khi đưa bơm vào vận hành cần thực hiện nội dung và thông số nào?','Motor bơm nóng bất thường: nêu nguyên nhân, cách kiểm tra và xử lý.','Kiểm tra định kỳ và bơm bổ sung mỡ cho bạc đạn motor bơm như thế nào?']}},
  vy:{name:'Vy',caption:'10 câu ATVSV/PCCC · 11 câu nước',topics:{'ATVSV / PCCC':['Nêu số hiệu, thời điểm ban hành, hiệu lực, bố cục và đối tượng áp dụng của Luật An toàn, vệ sinh lao động.','Nêu bố cục, đề mục các chương và nội dung hiệu lực thi hành của Luật An toàn, vệ sinh lao động.','Trình bày biện pháp cơ bản phòng, chống yếu tố nguy hiểm, có hại; nêu biện pháp thông tin, truyền thông, giáo dục.','Nêu trách nhiệm của người sử dụng lao động theo Luật An toàn, vệ sinh lao động.','Nêu trách nhiệm của người lao động theo Luật An toàn, vệ sinh lao động.','Nghị định 44/2016/NĐ-CP quy định nội dung gì; nêu bố cục, phạm vi điều chỉnh và đối tượng áp dụng.','Đối tượng huấn luyện an toàn, vệ sinh lao động theo Nghị định 44/2016/NĐ-CP gồm bao nhiêu nhóm và nội dung từng nhóm?','Nêu và phân tích điều kiện cần thiết cho sự cháy; liên hệ biện pháp phòng, chống cháy tại đơn vị.','Nêu nguyên nhân gây cháy trong sản xuất kinh doanh.','Trình bày trình tự thực hiện Garo vết thương tại 1/3 dưới cẳng tay trái.'],'Nước':['Nêu nguyên tắc và quy trình Jartest mẫu nước thô.','Trình bày xử lý sự cố khẩn cấp chất lượng nước khi nguồn nước bị ô nhiễm.','Trình bày xử lý sự cố khẩn cấp chất lượng nước khi có dịch bệnh nguy cơ ảnh hưởng diện rộng.','Nêu yêu cầu chung đối với cán bộ thiết kế lắp đặt đồng hồ nước theo QĐ-CTY-100.','Trình bày trách nhiệm công nhân vận hành hệ thống cấp nước trong ca trực đối với máy bơm.','Nước tự dùng cho hệ thống cấp nước là gì? Tổng lượng nước tự dùng theo TCVN 13606:2023 là bao nhiêu?','Mục đích xả rửa bể chứa là gì? Quy định súc rửa bể chứa như thế nào?','Nêu nguyên tắc chung trong công tác kiểm tra bể lọc, bể lắng.','Liệt kê trình tự các bước xử lý sự cố đột xuất trên mạng ống cấp nước.','Trình bày nội dung bắt buộc khi xử lý sự cố xì bể tuyến ống theo QĐ-CTY-123.','Trình bày cách ghi chỉ số trên hộp số các đồng hồ nước hiện nay do Công ty quản lý.']}}
};
const sources = {
  kha: { file: './data/kha.md', groups: [['Thực hành', 12]] },
  tu: { file: './data/tu.md', groups: [['Điện', 12], ['Nước', 8]] },
  vy: { file: './data/vy.md', groups: [['ATVSV / PCCC', 10], ['Nước', 11]] }
};
let person=null,topic='Tất cả',last=null;
const candidates=document.querySelector('#candidate-list'),topics=document.querySelector('#topic-list'),note=document.querySelector('#pool-note'),desc=document.querySelector('#topic-description'),btn=document.querySelector('#draw-button'),wrap=document.querySelector('#question-wrap'),label=document.querySelector('#draw-label'),dice=document.querySelector('#dice');
function pool(){if(!person)return[];const t=banks[person].topics;const make=(item,k,i)=>typeof item==='string'?{topic:k,index:i+1,text:item,answer:''}:{topic:k,index:i+1,text:item.text,answer:item.answer,label:item.label};return topic==='Tất cả'?Object.keys(t).flatMap(k=>t[k].map((item,i)=>make(item,k,i))):t[topic].map((item,i)=>make(item,topic,i));}
function renderPeople(){candidates.innerHTML=Object.keys(banks).map(k=>'<button class="candidate '+(k===person?'active':'')+'" data-p="'+k+'"><strong>'+banks[k].name+'</strong><small>'+banks[k].caption+'</small></button>').join('');candidates.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{person=b.dataset.p;topic='Tất cả';last=null;wrap.innerHTML='<p class="question-placeholder">Đã chọn thí sinh. Chọn chủ đề hoặc quay toàn bộ câu hỏi.</p>';label.textContent='Bộ câu hỏi của '+banks[person].name+' đã sẵn sàng';renderPeople();renderTopics();});}
function renderTopics(){if(!person)return;const names=['Tất cả'].concat(Object.keys(banks[person].topics));desc.textContent='Chọn “Tất cả” để trộn toàn bộ, hoặc chỉ quay trong một chủ đề.';topics.innerHTML=names.map(k=>'<button class="topic '+(k===topic?'active':'')+'" data-t="'+k+'">'+k+'</button>').join('');topics.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{topic=b.dataset.t;last=null;renderTopics();});btn.disabled=false;note.textContent=(topic==='Tất cả'?'Toàn bộ ngân hàng':'Chủ đề '+topic)+': '+pool().length+' câu hỏi.';}
btn.onclick=()=>{const all=pool(),available=all.length>1?all.filter(q=>!last||q.text!==last.text):all,q=available[Math.floor(Math.random()*available.length)];last=q;btn.disabled=true;dice.classList.add('rolling');label.textContent='Đang quay...';setTimeout(()=>{dice.classList.remove('rolling');label.textContent=banks[person].name+' · '+q.topic;const answer=q.answer?'<button class="answer-toggle" type="button">👁 Hiện đáp án tham khảo</button><div class="answer-panel" hidden><div class="answer-title">ĐÁP ÁN THAM KHẢO</div><div class="answer-content">'+q.answer+'</div></div>':'';wrap.innerHTML='<div><div class="question-number">CÂU TỰ LUẬN · '+q.topic.toUpperCase()+'</div><p class="question-text">'+q.text+'</p>'+answer+'</div>';const toggle=wrap.querySelector('.answer-toggle');if(toggle)toggle.onclick=()=>{const panel=wrap.querySelector('.answer-panel'),hidden=panel.hidden;panel.hidden=!hidden;toggle.textContent=hidden?'🙈 Ẩn đáp án tham khảo':'👁 Hiện đáp án tham khảo';};btn.disabled=false;},650);};
function parseQuestions(markdown){const parts=markdown.split(/^## (Câu(?: hỏi)?\s*\d+\s*[:.]?.*)$/m),items=[];for(let i=1;i<parts.length;i+=2){const heading=parts[i].trim(),body=parts[i+1]||'',marker=body.search(/^### /m),prompt=(marker<0?body:body.slice(0,marker)).trim(),answerBlock=marker<0?'':body.slice(marker).trim(),firstBreak=answerBlock.indexOf('\n'),answerHeading=(firstBreak<0?answerBlock:answerBlock.slice(0,firstBreak)).replace(/^###\s*/,'').replace(/^(Gợi ý\s*)?(Đáp án|Trả lời)\s*:?\s*/i,''),answerBody=firstBreak<0?'':answerBlock.slice(firstBreak+1).trim(),answer=(answerHeading+(answerHeading&&answerBody?'\n\n':'')+answerBody).trim(),simple=/^Câu\s*\d+\s*[:.]?$/.test(heading);items.push({label:heading,text:simple?heading+'\n'+prompt:heading,answer});}return items;}
Promise.all(Object.entries(sources).map(async ([key,source])=>{const response=await fetch(source.file,{cache:'no-store'});if(!response.ok)throw new Error(source.file);const questions=parseQuestions(await response.text()),topics={};let offset=0;source.groups.forEach(([name,count])=>{topics[name]=questions.slice(offset,offset+count);offset+=count;});if(questions.length!==offset)throw new Error('Sai số lượng câu của '+key);banks[key].topics=topics;})).then(renderPeople).catch(error=>{console.error(error);renderPeople();wrap.innerHTML='<p class="question-placeholder">Đang dùng ngân hàng dự phòng. Hãy làm mới trang để tải dữ liệu đầy đủ.</p>';});
